### ISSUE TITLE
viz timeline item text overflow

### ISSUE THREAD

**Issue by lea-horn** [razbensimon/react-vis-timeline#13]
# Overview
I have a timeline with a lot of information, i.e .: a lot of details, and for each long text item,
So it certainly happens that the text of one item exceeds the text of another item,
It would be good for me if the text slides downwards, the question is will it then exceed the groups below it? Is there support for this?

**Comment by razbensimon** [comment]
search for `vis-timeline` library docs for solutions.
this lib is just a React api wrapper.
