### ISSUE TITLE
How to save timeline data ?

### ISSUE THREAD

**Issue by stevenpersia** [razbensimon/react-vis-timeline#17]
Yo !

First of all, thank you for your work. This is excellent :heart: 

But I want to know, how can I save processed items on my timeline in a database ? Is that possible to access of all data and send it to my backend ?

Or I need to handle it on each events like `onAdd`, `onRemove`, ... ? I'm not confident on this solution because it will make a lot of requests on my backend.

Thank you for your advices !

**Comment by razbensimon** [comment]
hey, this is an UI library. you need to handle your data and BE yourself...

**Comment by stevenpersia** [comment]
Not exactly what I asked but thank you for your time/package. :wave:
