### ISSUE TITLE
Groups order is incorrect when there are 3 or more levels

### ISSUE THREAD

**Issue by the-user-123456** [razbensimon/react-vis-timeline#5]
# Overview
I need to create Group structure with 3 (may be more in the future) levels. However, 3rd and deeper level groups are not displayed under their respective parent, but instead I get either all 2nd level, then all 3rd level, then all 4th level groups, or unexpected order.

I tried:
    - setting the IDs so they grow with the visual order
    - setting them so they grow with the tree level
    - adding only direct subgroups to the nestedGroups array
    - adding all levels of subgroups to the nestedGroups array
And the combinations of the above. Nothing works.

Also took the group structure from this correctly working example and it too didn't work:
[https://visjs.github.io/vis-timeline/examples/timeline/groups/nestedThreeLevels.html](url)

## Package versions
    "react-visjs-timeline": "1.5.0",
    "vis": "^4.20.1",
    "vis-timeline": "^7.4.2",

## Code Snippet

```
let options = {start: moment(), end: moment().add(1, 'days')};
let groups = [
    {id: 1, treeLevel: 1, content: "1", nestedGroups: [2, 4, 7]},
    {id: 2, treeLevel: 2, content: "2", nestedGroups: [3]},
    {id: 3, treeLevel: 3, content: "3"},
    {id: 4, treeLevel: 2, content: "4", nestedGroups: [5]},
    {id: 5, treeLevel: 3, content: "5", nestedGroups: [6]},
    {id: 6, treeLevel: 4, content: "6"},
    {id: 7, treeLevel: 2, content: "7", nestedGroups: [8]},
    {id: 8, treeLevel: 3, content: "8", nestedGroups: [9]},
    {id: 9, treeLevel: 4, content: "9"},
];
return <Timeline options={options} groups={groups} />
```

Expexted order: 1, 2, 3, 4, 5, 6, 7, 8, 9
Actual order: 1, 2, 4, 7, 3, 5, 6, 8, 9

## Related issues
none

## Screenshots (if appropriate)

<img width="86" alt="Screenshot 2020-11-12 at 17 37 18" src="https://user-images.githubusercontent.com/46609775/98960992-bd8eff80-250d-11eb-90b9-11ec3a0eaea5.png">

**Comment by razbensimon** [comment]
From a first look, it's not related to this library. open the issue at `vis-timeline`
