### ISSUE TITLE
Cannot get basic example to work

### ISSUE THREAD

**Issue by FranzThomsen1089** [razbensimon/react-vis-timeline#51]
I am consistently getting an error

Uncaught TypeError: this._data.getIds is not a function
    at DataView.setData (data-view.ts:155:1)
    at new DataView (data-view.ts:119:1)
    at Timeline.setGroups (Timeline.js:353:1)
    at new Timeline (Timeline.js:245:1)

I have tried starting from scratch

npx create-react-app my-app --template typescript 

where I have added

"react-vis-timeline": "2.0.3"

and then since that seems to have unmet dependencies, I ended up adding 

    "web-vitals": "^2.1.4",
    "vis-timeline": "^7.4.2",
    "lodash": "4.17.21",
    "moment": "2.29.1",
    "xss": "^1.0.11",
    "vis-data": "^7.1.4"

Then using the code from https://github.com/razbensimon/react-vis-timeline/blob/master/examples/src/App.js to the main App.tsx, renamed to js

I am not sure why I am getting above error, or of course how to resolve it. Any help is appreciated

**Comment by selmabhellum** [comment]
Hi! Did you ever find the solution to this error? Currently experiencing the same issue.

**Comment by FranzThomsen1089** [comment]
Gave up, not worth it. Bought mobiscroll
